version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khovaiton-frontend
    ports:
      - "3004:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - khovaiton-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend Express.js API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: khovaiton-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - khovaiton-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  khovaiton-network:
    driver: bridge

volumes:
  # Add any persistent volumes here if needed
  node_modules_cache:
    driver: local
